<?php  if ( ! defined("BASEPATH")) exit("No direct script access allowed");
$config["protocol"]="smtp";
$config["smtp_host"]="ssl://smtp.googlemail.com";
$config["smtp_port"]="465";
$config["smtp_timeout"]="30";
$config["smtp_user"]="test@example.com";
$config["smtp_pass"]="1234";
$config["charset"]="utf-8";
$config["newline"]="\r\n";
$config["mailtype"]="html";
